# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190420_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 18, 50, 44, 924050, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 18, 50, 44, 924112, tzinfo=utc)),
        ),
    ]
